Sprint 7: exercises
SberKotlinSchool/Sprint-7 pull request #35
Opened 2023-01-22 18:39 UTC by vadim991-tt

2023-01-22 18:42 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-data, spring-security, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/1676/

2023-01-22 18:52 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-security, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/1677/

2023-01-22 19:01 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/1678/

2023-01-29 16:19 UTC, SberKotlinSchool commented on rdbms/src/main/kotlin/ru/sber/rdbms/TransferOptimisticLock.kt
> +                    if (updatedRows.isEmpty())
если будет обновлен ровно один аккаунт?

2023-01-30 16:12 UTC, SharikTLT reviewed
spring security принято без замечаний

2023-02-03 17:37 UTC, vadim991-tt commented on rdbms/src/main/kotlin/ru/sber/rdbms/TransferOptimisticLock.kt
> +                    if (updatedRows.isEmpty())
Если мы обновим только один аккаунт и не сможем второй - упадем с ошибкой и откатим транзакцию.

2023-06-18 16:42 UTC, closed without merging