sprint-7
SberKotlinSchool/Sprint-7 pull request #48
Opened 2023-12-09 12:40 UTC by ShedowSith

2023-12-09 12:41 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules orm, spring-data, spring-security, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/656/

2023-12-09 16:37 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-data, spring-security, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/657/

2023-12-10 09:55 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-data, spring-security, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/666/

2023-12-10 16:51 UTC, SberKotlinSchool commented on rdbms/src/main/kotlin/ru/sber/rdbms/TransferPessimisticLock.kt
>      fun transfer(accountId1: Long, accountId2: Long, amount: Long) {
Не учтен дедлок

2023-12-11 19:12 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-data, spring-security, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/703/

2023-12-11 19:39 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-data, spring-security, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/704/

2023-12-13 18:10 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/730/

2023-12-13 18:16 UTC, SharikTLT commented on spring-security/src/test/kotlin/ru.shadowsith.addressbook.controllers/AddressBookApiControllerTest.kt
> +    @Disabled
тесты отключены из-за того, что httpBasic аутентификация не подключена для /api ?

2023-12-13 18:16 UTC, SharikTLT reviewed
spring-security выполнено с незначительным комментарием

2023-12-17 09:29 UTC, ShedowSith commented on spring-security/src/test/kotlin/ru.shadowsith.addressbook.controllers/AddressBookApiControllerTest.kt
> +    @Disabled
Да

2025-05-19 19:18 UTC, closed without merging