Sprint-7 hw
SberKotlinSchool/Sprint-7 pull request #58
Opened 2023-12-16 14:44 UTC by DOKL57

Здравствуйте! Проверьте, пожалуйста.

P.S. В Spring security не обновил тесты с версии spring mvc

2023-12-16 14:46 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules orm, spring-security, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/748/

2023-12-18 08:33 UTC, SharikTLT commented on spring-security/src/test/kotlin/com/dokl57/springmvc/controller/MvcControllerTest.kt
> +class MvcControllerTest {
для тестов ведь есть хорошие инструменты для тестирования, как минимум для MockMvc подхода :) в живых проектах никто с упавшими тестами не пропустит ПР. Тем более в задании было требование дополнить тесты.
Пока оставлю это на доработку, если не будете успевать - свяжитесь пожалуйста со мной.

- [ ] вернуться к исправлению тестов

2023-12-18 15:19 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules orm, spring-security, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/789/

2023-12-18 15:34 UTC, DOKL57 commented on spring-security/src/test/kotlin/com/dokl57/springmvc/controller/MvcControllerTest.kt
> +class MvcControllerTest {
Спасибо за комментарий! Добавил тесты для MVC. В sberUniversity стоял дедлайн 17 декабря, к нему сразу не успел. Что же касается "живых проектов", мне кажется, тут помимо замечаний от условного сонара за недостаточное прокрытие тестами, а точнее их отсутствие, прилетело бы и от проверяющих. Качество кода в целом так себе, наверняка есть, что исправить)
К сожалению, сейчас под новый год навалились более приоритетные задачи, нежели курсы, поэтому пока не получается уделять выполнению заданий достаточно времени.
Судя по логам дженкинса, не получилось собраться  с 17 джавой, локально все тесты корректно отрабатывают.

2024-02-15 19:15 UTC, closed without merging